### ISSUE TITLE
Disable ssl

### ISSUE THREAD

**Issue by nikolasj** [pederhan/harborapi#42]
Hello. Is it possible to disable certificate verification?
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)
```
in requests package it is verify=False
requests.get(policy_url, headers=HEADERS, auth=(username, password), verify=False)

**Comment by pederhan** [comment]
Yeah, I can add that, although I am using [httpx](https://www.python-httpx.org/advanced/#ssl-certificates), which might have a slightly different implementation.

I'll probably just expose _all_ `httpx.AsyncClient` kwargs in the `HarborAsyncClient` in the constructor at some point, but I'll prioritize adding `verify` ASAP.

**Comment by nikolasj** [comment]
Thank you. A very necessary feature. I would like to try to use your lib

**Comment by pederhan** [comment]
I've pushed a new version (0.14.1), try it out and see if it works for you.

**Comment by nikolasj** [comment]
It works for me. Thank you!
