### ISSUE TITLE
Add endpoint for Create Retention Policy

### ISSUE THREAD

**Issue by nikolasj** [pederhan/harborapi#44]
Now I have not found an endpoint for creating a retention policy. Can you add? I would also like to see an example.

**Comment by pederhan** [comment]
I have not added that yet. I will add it some time in the next couple of days.

**Comment by nikolasj** [comment]
Thanks, I'll wait. A very necessary endpoint.

**Comment by pederhan** [comment]
This has been added in v0.15.0. There is some rudimentary documentation for how to interact with this endpoint on the [Recipes](https://pederhan.github.io/harborapi/recipes/retention/get-retention/) page. Also check out the API reference for the different endpoints [here](https://pederhan.github.io/harborapi/endpoints/retention/).

Try it out and see how it works for you.

**Comment by pederhan** [comment]
I've played with it a bit myself now, and I have to say the API endpoints are a bit of an undocumented mess... You can definitely reverse-engineer it by creating retention rules in the web interface, then inspecting the resulting policy data from the API, but it's not ideal.

The API relies on magic string variables to denote the different retention rules and strategies, none of which are documented in the official API spec. So while these new methods should definitely work, it's not really feasible for me to document all the possible values that can be assigned to a `RetentionPolicy` object.

Take for instance this rule in the web interface:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/107681714/231734084-bd555a0a-0029-4107-9de7-83d43ec425ce.png">

Results in this policy (JSON representation):

```json
{
  "id": 1,
  "algorithm": "or",
  "rules": [
    {
      "id": null,
      "priority": null,
      "disabled": null,
      "action": "retain",
      "template": "latestPushedK",
      "params": {
        "latestPushedK": 5
      },
      "tag_selectors": [
        {
          "kind": "doublestar",
          "decoration": "matches",
          "pattern": "**",
          "extras": "{\"untagged\":true}"
        }
      ],
      "scope_selectors": {
        "repository": [
          {
            "kind": "doublestar",
            "decoration": "repoMatches",
            "pattern": "**",
            "extras": null
          }
        ]
      }
    }
  ],
  "trigger": {
    "kind": "Schedule",
    "settings": {
      "cron": ""
    },
    "references": null
  },
  "scope": {
    "level": "project",
    "ref": 7
  }
}
```

You can see stuff like `"doublestar"`, `"matches"` and `"repoMatches"`. None of which are documented in the API spec.

**Comment by nikolasj** [comment]
Thank you! Now I will check.
Could you tell me in your example the scope section refers to the project? i.e. ref: 7 is the project id?

**Comment by nikolasj** [comment]
Can you help me?
I am getting an error trying to set the rules

```
from harborapi.models.models import RetentionPolicy, RetentionRule
rule = {
    "id": 258246,
    "algorithm": "or",
    "rules": [
        {
            "action": "retain",
            "template": "latestPushedK",
            "params": {
                "latestPushedK": 5
            },
            "tag_selectors": [
                {
                    "kind": "doublestar",
                    "decoration": "matches",
                    "pattern": "**",
                    "extras": "{\"untagged\":true}"
                }
            ],
            "scope_selectors": {
                "repository": [
                    {
                        "kind": "doublestar",
                        "decoration": "repoMatches",
                        "pattern": "**"
                    }
                ]
            }
        }
    ],
    "trigger": {
        "kind": "Schedule",
        "settings": {
            "cron": ""
        },
    },
    "scope": {
        "level": "project",
        "ref": 258246
    }
}

retention_rule = RetentionRule(rule)
policies = []
policies.append(retention_rule)
policy = RetentionPolicy(policies)
```

```
Traceback (most recent call last):
  File "/home/nikolai/src/harbor_api.py", line 59, in <module>
    retention_rule = RetentionRule(rule)
  File "pydantic/main.py", line 332, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)
```

**Comment by pederhan** [comment]
> ref: 7 is the project id?

Yes. Call `get_retention_policy()` with the retention ID you get from `get_project_retention_id()`, and you should get a similar policy object.

Just call `.json()` on the returned policy object if you want a similar JSON representation.

**Comment by pederhan** [comment]
I'll try to add some syntactic sugar to the retention endpoint methods in the future if Harbor doesn't provide a better API schema for it, but I don't have time right now. So I'm closing this issue for now, as the general API spec compliant methods are now implemented.
