### ISSUE TITLE
get_project method throws a Client error 422 unprocessable

### ISSUE THREAD

**Issue by Winspain** [pederhan/harborapi#55]
"My Harbor version is v2.1.3. When I use the get_project method and pass the project_name parameter, it  entity for the URL [http://xxxxx/api/v2.0/projects/{project_name}](http://xxxxx/api/v2.0/projects/%7Bproject_name%7D)."

**Comment by pederhan** [comment]
In your version of Harbor, only project IDs can be used to fetch projects:

https://github.com/goharbor/harbor/blob/b6de84c57111ff74afb602691647ca548d4667d1/api/v2.0/swagger.yaml#L112-L130

**Comment by pederhan** [comment]
Closing this issue since I cannot do anything about it.
