### ISSUE TITLE
[New Feature] purgeaudit

### ISSUE THREAD

**Issue by teimyBr** [pederhan/harborapi#78]
[New Feature] enable purgeaudit

This helps that the harbor db not get over filled and keeps clean.

API Call: "/api/v2.0/system/purgeaudit/schedule"

Would be nice if the python package support this api call 

Would help that Project
 [Issue](https://github.com/steadforce/harbor-day2-operator/issues/4)

**Comment by pederhan** [comment]
Sorry, I've been very busy the past month. I am working on adding this right now.

**Comment by pederhan** [comment]
https://unioslo.github.io/harborapi/endpoints/purge/

**Comment by peters-david** [comment]
Thank you for adding this!
Is there a possibility to fetch all existing purge jobs (and schedules)? I would like to be able to get a list of all existing purge jobs so I can remove or stop the incorrect ones.
